### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by MathieuUrstein** [MathieuUrstein/HEIG.TWEB.Project02#1]
- [x] Remove mongo for frontend step
- [x] Poll participation view
- [x] Poll results view
- [x] Readme
- [x] Deploy
- [x] Delete element validation (ex: answer, slips)
- [x] Loading spinner
- [x] Create footer
- [x] Multi devices landing page icon
- [x] Multiple propositions for polls
- [x] Better connection handling (admin pages)
- [x] Keep data loss for poll creation route switch
- [x] Restrict socket messages if logged in
- [x] Reduce connection messages
- [x] Delete polls
- [x] socket.off("channel");
- [x] socket.on() -> ngOnInit()
- [x] Do not let reanswer
---
- [ ] Refactor polls methods (singleSelect(), multiSelect()...)
- [ ] Pages transitions
- [ ] Refactor scss
- [ ] Reorder polls
- [ ] Security
   - [x] Hash passwords
   - [x] Add owner of polls in backend
   - [ ] Given data assertions
   - [ ] Backend message validation
   - [ ] Remove direct html display in questions
- [ ] Unit tests
- [ ] Subscribe -> ngOnInit(), UnSubscribe -> ngOnDestroy()
- [ ] Comments
- [ ] Divide messages functions in multiple files
- [ ] Display percents in results mobile views
- [ ] Display number of participents
- [ ] Url random string distribution
- [ ] Full amin page
- [ ] Remove livereload from production
